version: ci-{build}-{branch}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: eHI+nPFCmnPOdRRPRhGQBso/RlA5seuhkPBRgOMbGWDHzNWw+Us1FJrR7TTBLVR0
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: 4YnW39HkIvwf3bMJPyaoHweSw6rQ00REWeUr0PnUozmOzSkHJ0xdepdCc1ZELBuv
  on:
    appveyor_repo_tag: true
